name: Build and Publish Docker
run-name: Build and Publish Docker by ${{ gitea.actor }}

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: gitea.cloud1ful.com
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GTCR }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gitea.cloud1ful.com/${{ github.repository }}:latest
          cache-from: |
            type=registry,ref=gitea.cloud1ful.com/${{ github.repository }}:buildcache
            type=registry,ref=gitea.cloud1ful.com/${{ github.repository }}:latest
          cache-to: type=registry,ref=gitea.cloud1ful.com/${{ github.repository }}:buildcache,mode=max
