[package]
name = "redactor-chat-responses-proxy"
version.workspace = true
edition.workspace = true
publish = false
repository.workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
axum.workspace = true
futures-util.workspace = true
redactor = { package = "cloudiful-redactor", path = "../redactor" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
