[package]
name = "redactor-http"
version.workspace = true
edition.workspace = true
publish = false
repository.workspace = true

[features]
default = []
chat-responses-proxy = ["dep:redactor-chat-responses-proxy"]

[dependencies]
anyhow.workspace = true
axum.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
server.workspace = true
tokio.workspace = true
redactor = { package = "cloudiful-redactor", path = "../redactor" }
redactor-chat-responses-proxy = { path = "../redactor-chat-responses-proxy", optional = true }

[dev-dependencies]
tower.workspace = true
