[package]
name = "redactor-http"
version.workspace = true
edition.workspace = true
publish = false
repository.workspace = true

[features]
default = []
valkey-session-store = ["dep:redactor-session-store-valkey"]

[dependencies]
anyhow.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
server.workspace = true
tokio.workspace = true
redactor = { package = "cloudiful-redactor", path = "../redactor" }
redactor-session-store-valkey = { path = "../redactor-session-store-valkey", optional = true }

[dev-dependencies]
tower.workspace = true
